#if !canImport(ObjectiveC)
import XCTest

extension HighPrecisionNumberTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HighPrecisionNumberTests = [
        ("testHighPrecisionNumberParsingFails", testHighPrecisionNumberParsingFails),
        ("testHighPrecisionNumberStandardParsing2", testHighPrecisionNumberStandardParsing2),
        ("testHighPrecisionNumberStandardParsing3", testHighPrecisionNumberStandardParsing3),
        ("testHighPrecisionNumberStandardParsing4", testHighPrecisionNumberStandardParsing4),
        ("testHighPrecisionNumberStandardParsing5", testHighPrecisionNumberStandardParsing5),
        ("testHighPrecisionNumberStandardParsing6", testHighPrecisionNumberStandardParsing6),
        ("testHighPrecisionNumberStandardParsing", testHighPrecisionNumberStandardParsing),
    ]
}

extension UBJSONSerializationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UBJSONSerializationTests = [
        ("testDecodeBigOptimizedArray", testDecodeBigOptimizedArray),
        ("testDecodeNil", testDecodeNil),
        ("testDecodeNop", testDecodeNop),
        ("testDecodeSimpleObject", testDecodeSimpleObject),
        ("testEncodeInt8", testEncodeInt8),
        ("testEncodeNil", testEncodeNil),
        ("testEncodeNop", testEncodeNop),
        ("testEncodeOptimizedArrayOfInts", testEncodeOptimizedArrayOfInts),
        ("testEncodeSimpleObject", testEncodeSimpleObject),
        ("testGarbageAtEndError", testGarbageAtEndError),
        ("testNopSkipping", testNopSkipping),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HighPrecisionNumberTests.__allTests__HighPrecisionNumberTests),
        testCase(UBJSONSerializationTests.__allTests__UBJSONSerializationTests),
    ]
}
#endif
